# Generated by Django 4.1.1 on 2022-10-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, max_length=500)),
                ('link_img', models.CharField(blank=True, max_length=500)),
                ('qtd_marmitas', models.IntegerField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'kits',
            },
        ),
        migrations.CreateModel(
            name='Marmita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, max_length=500)),
                ('link_img', models.CharField(blank=True, max_length=500)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'marmitas',
            },
        ),
    ]
