# Generated by Django 4.1.1 on 2022-10-27 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_marmita_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeioPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('link_img', models.CharField(blank=True, max_length=500)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'meios_pagamento',
            },
        ),
        migrations.AlterField(
            model_name='marmita',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
