# Generated by Django 4.1.1 on 2022-11-03 00:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_enderecosentrega_cidade'),
        ('pedidos', '0004_rename_meiopagamento_meiospagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.kit')),
            ],
            options={
                'db_table': 'kits_pedidos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'Realizado'), ('V', 'Validado'), ('S', 'Separado'), ('D', 'Despachado'), ('E', 'Entregue'), ('C', 'Cancelado')], max_length=1)),
                ('data_emissao', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.enderecosentrega')),
                ('meio_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.meiospagamento')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='MarmitaKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_marmita', models.IntegerField()),
                ('kit_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.kitpedido')),
                ('marmita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.marmita')),
            ],
            options={
                'db_table': 'marmitas_kit',
            },
        ),
        migrations.AddField(
            model_name='kitpedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
        migrations.AddConstraint(
            model_name='marmitakit',
            constraint=models.UniqueConstraint(fields=('kit_pedido', 'marmita'), name='unique_primaryKey'),
        ),
    ]
