# Generated by Django 4.1.1 on 2022-10-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EderecoEntrega',
            new_name='EnderecosEntrega',
        ),
    ]
