# Generated by Django 4.1.1 on 2022-10-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_ederecoentrega_enderecosentrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecosentrega',
            name='cidade',
            field=models.CharField(default='São Paulo', max_length=50),
            preserve_default=False,
        ),
    ]
